# Generated by Django 3.2.12 on 2023-03-02 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('recipe_yield', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('recipe_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
